services:

  emerald-seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: emerald-seaweedfs
    ports:
      - "19333:9333"   # Master + Master UI
      - "19340:9340"   # Volume
      - "18888:8888"   # Filer UI
      - "18333:8333"   # S3
      - "17333:7333"   # WebDAV
      - "13646:23646" # ★ Admin UI
    command: >
      mini
        -dir=/data
        -ip=emerald-seaweedfs
        -ip.bind=0.0.0.0
        -master.port=9333
        -volume.port=9340
        -filer.port=8888
        -s3.port=8333
        -admin.port=23646
    volumes:
      - emerald_seaweedfs_data:/data
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  emerald_seaweedfs_data:

networks:
  shared-network:
    external: true
    name: emerald-infra-net